name: Deploy

on:
  push:
    branches:
      - v2DevOps
  # workflow_dispatch:
  #  inputs:
  #    resourceGroupName:
  #      description: 'Name of the resource group'
  #      default: 'rg-logic-app-pattern'
  #      required: true  
env:
  LOCATION: 'eastus'
  RESOURCE_GROUP_NAME: 'rg-logic-app-pattern'
  #RESOURCE_GROUP_NAME: ${{ github.event.inputs.resourceGroupName }}

jobs:
  create-azure-resources:

    runs-on: ubuntu-latest

    outputs:      
      functionProcessorName: ${{ steps.armDeployment.outputs.functionProcessorName }}      
      logicAppName: ${{ steps.armDeployment.outputs.logicAppName }}

    steps:
      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}

      - name: Create Resource Group
        run: |
          az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}            

      # Temporary step the bicep linter return an error today for the
      # scope in the RBAC assignments
      - name: Convert to ARM template
        run: |
          bicep build ./bicep/main.bicep

      - name: Deploy Azure Resources
        id: armDeployment
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./bicep/main.json
          parameters: location=${{ env.LOCATION }} clientId=${{ secrets.SP_CLIENT_ID }} clientSecret=${{ secrets.SP_CLIENT_SECRET }}

  deploy-function-processor:
    
    needs: create-azure-resources

    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_PROCESSOR_PACKAGE_PATH: 'src/function/processor'
      
    steps:

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}  

      - name: Setup DotNet 3.1.X Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'    

      - name: 'Building Processor'
        shell: bash
        run: |
          pushd './${{ env.AZURE_WEBAPP_PROCESSOR_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Deploy Functions Processor'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.create-azure-resources.outputs.functionProcessorName }}
          package: '${{ env.AZURE_WEBAPP_PROCESSOR_PACKAGE_PATH }}/output'           

