name: Deploy

on:
  push:
    paths:
      - 'bicep/**'
  workflow_dispatch:
  
env:
  LOCATION: 'eastus'
  RESOURCE_GROUP_NAME: 'rg-logic-app-pattern-2'

jobs:
  create-azure-resources:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}

      - name: Create Resource Group
        run: |
          az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}            

      # Temporary step the bicep linter return an error today for the
      # scope in the RBAC assignments
      - name: Convert to ARM template
        run: |
          bicep build ./bicep/main.bicep

      - name: Deploy Azure Resources
        id: armDeployment
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./bicep/main.json
          parameters: location=${{ env.LOCATION }}

      - uses: gliech/create-github-secret-action@v1
        with:
          name: DESTINATION_STORAGE_ID
          value: ${{ steps.armDeployment.outputs.destinationStorageId }}
          pa_token: ${{ secrets.PA_TOKEN }}

      - uses: gliech/create-github-secret-action@v1
        with:
          name: SOURCE_STORAGE_NAME
          value: ${{ steps.armDeployment.outputs.sourceStorageName }}
          pa_token: ${{ secrets.PA_TOKEN }}     

      - uses: gliech/create-github-secret-action@v1
        with:
          name: SYSTEM_IDENTITY_ID
          value: ${{ steps.armDeployment.outputs.systemIdentityId }}
          pa_token: ${{ secrets.PA_TOKEN }}           